
theme: jekyll-theme-chirpy

# 全局语言，例如将侧边的“home”改成“主页”等，可选项在_data/locales/下
lang: zh-CN

# 时区
timezone: Asia/Shanghai
 
# 站点标题，显示在网站标签页和左上角
title: Hin小站 # the main title

# 站点副标题，在标题之下
tagline: 时间太瘦，指缝太宽。 

# 站点描述，用于搜索引擎优化，改不改问题不大
description: 

# 站点域名，注意结尾不包括 '/'。
url: "https://hintryer.github.io"

# github名，改成自己的github名字
github:
  username: hintryer
  
# twitter名，改成自己的twitter名字
#twitter:
#  username: twitter_username 

### 自己的社交帐号信息，在页脚中显示为文章的默认作者和版权所有者。
social:
  name: Hin所有
  email: example@domain.com 
  links:
    # 第一个元素用作版权所有者的链接，在下方取消注释以添加更多社交链接
    - https://github.com/hintryer/hintryer.github.io
    - https://h2o-ac-doc.lisz.me/basic/config.html
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 站点验证设置，默认为空
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# 网页分析设置，默认为空
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

# 页面查看次数设置，现在只支持'goatcounter'，默认为空
pageviews:
  provider: 

# 首选颜色方案设置。留空将默认遵循系统首选颜色，并且在侧边栏的左下角会有一个开关来在深色和浅色之间切换主题

theme_mode: # [light | dark]

# 媒体资源的 CDN 地址。
cdn: ""

# 侧边栏头像，支持本地或 CORS 资源
avatar: "/assets/img/favicons/apple-touch-icon.png"

# 社交预览图像，没什么用
social_preview_image: # string, local or CORS resources

# 博客中目录的全局开关。true | false
toc: true

# 评论相关，默认禁用。
comments:
  # 帖子评论系统的全局开关。将其留空表示禁用。
  provider: # [disqus | utterances | giscus]
  # The provider options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# 自托管静态资产，没什么用。留空禁止
assets:
  self_host:
    enabled: # boolean, keep empty means false
    env: # [development | production]
#PWA有关
pwa:
  enabled: true # The option for PWA feature (installable)
  cache:
    enabled: true # The option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA
      
# 分页
paginate: 10

# The base URL of your site
baseurl: ""

# 不建议修改以下选项

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"  #定义应用于脚注反向链接的文本
  syntax_highlighter: rouge #设置语法高亮器
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    default_lang: JavaScript
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
